# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Hello GitHub Actions

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  greet:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: verfiy node js installation
        run: |
          node -v
          npm -v

      - name: Print Message
        run: echo "Hello GitHub Actions ðŸš€"

      - name: Print present working directory
        run: pwd

      - name: List files in the repository
        run: ls -la
